### ISSUE TITLE
Github module is only checking last 100 commits

### ISSUE THREAD

**Issue by Te-k** [Nhoya/gOSINT#1]
To get the list of commits`gitAPI.go` calls the API manually with an url like https://api.github.com/repos/PyGithub/PyGithub/commits?per_page=5000. The last parameter does not seem to have any effect, only the last 100 commits are actually returned by this page.

It would be better to get all of them, only solution I know is to use the API (which is really slow for large repos)

**Comment by Nhoya** [comment]
Yea, seems that if per_page is > 100 it set it back to 100, the solution is to implement [pagination](https://developer.github.com/v3/guides/traversing-with-pagination/)

**Comment by Nhoya** [comment]
The pagination for GitHub should work now, feel free to test it and give a feedback :)

Please remember that according to [GitHub doc](https://developer.github.com/v3/#rate-limiting),  the rate limit for unauthenticated requests is 60.

P.S. BitBucket pagination is not yet implemented

**Comment by Nhoya** [comment]
Update: The pagination should working for BitBucket too

Note: Have in mind that the scraper on BitBucket will check for all the commits of all the branches so may take a while on big repos

**Comment by Te-k** [comment]
Works for me
