### ISSUE TITLE
Run in Docker

### ISSUE THREAD

**Issue by duraki** [Nhoya/gOSINT#26]
As with many open-source tools, it's encouraged to create Dockerfile, and compose, to run the project in isolated, container environment.

**Comment by Nhoya** [comment]
Hi,
I like this idea but I think I'll wait the 1.0.0 release. If you want to contribute anyway feel free to open a PR

**Comment by Nhoya** [comment]
I pushed a dockerfile for the develop branch if you want to test it I'll be happy to hear your feedback

**Comment by duraki** [comment]
Ah, that was fast, we partly solved #25; great. I wrote a few comments on your patch. Testing in progress, will get back at you.

**Comment by Nhoya** [comment]
Any news about it?

**Comment by duraki** [comment]
Sorry for late delay. Seems that it works fine. Tested under latest MacOS Mojave.
